### ISSUE TITLE
List of Evidence terms?

### ISSUE THREAD

**Issue by vtoure** [vtoure/MICAST#4]
I guess it may happen that a specific causal statement is reported multiple times in different conditions: once experimentally, once computationally for example.

So, could we let the possibility to have a list of Evidence terms for a given causal interaction?

**Comment by ANiknejad** [comment]
I guess, yes, and at the end it could be possible to associate a confidence information to the causal statement using CIO ontology
http://www.obofoundry.org/ontology/cio.html
For example:
[Term]
id: CIO:0000006
name: confidence statement from multiple evidence lines of same type
def: "A confidence statement from multiple evidence lines, all using a same experimental or computational type." [Bgee:fbb]
is_a: CIO:0000002 ! confidence statement from multiple evidence lines
intersection_of: CIO:0000002 ! confidence statement from multiple evidence lines
intersection_of: has_evidence_type_concordance CIO:0000037 {all_only="true"} ! same type
disjoint_from: CIO:0000007 ! confidence statement from multiple evidence lines of multiple types
relationship: has_evidence_type_concordance CIO:0000037 ! same type

**Comment by stcruy** [comment]
For readers' information: this is how it stands in the latest (googledoc) version of the spec:

When there is a list of evidence terms, it means (similar to a list of references/PMIDs), that each of the terms brings a necessary but not sufficient part of the evidence, and that the whole list together forms a minimal set of necessary evidences that together support the causal statement.
It is necessary to support combinatory evidences, because curators sometimes infer a causal statement by combining information from multiple papers.

Note that the original question here was about multiple evidences (or actually sets of them) that would each independently support a statement.
My current recommendation is be to create a new causal statement for each, if it is deemed important to log all support. (A user-interface can support to easily copy+paste +edit a new evidence into the copy).
A future possibility could be to support graph structures like "evidenced-by either (ECO1 and ECO2) or ECO3 or ECO4", although that would add more structural complexity.

**Comment by vtoure** [comment]
Yes, the current way described in the guidelines is as you recommend, to provide a new causal statement for each evidence proving the causality
