### ISSUE TITLE
Cell type ontology recommendation

### ISSUE THREAD

**Issue by vtoure** [vtoure/MICAST#5]
The options were narrowed to three different ontologies to use for cell type: 

- BRENDA,

- Cellosaurus

- Cell Ontology (cell line or cell type). 

Could we recommend one to use? If not, could we prioritize which one to use mainly?

**Comment by ccasalsc** [comment]
I think most of us were feeling more comfortable using BRENDA but I guess both BRENDA and cellosaurus would be ok. About cell ontology, in my point of view, it should be used in a different column to define the cell/tissue type (together with UBERON) independently if they are primary cells or cell lines (if the cell type is well conserved for the cell line). 
For example, very often to study NK cells function, researchers use NKL cell line, in this case, in the way we build our PKN we will capture the information about the cell line: NKL (we weren't using ID's but we can start doing it) and the cell type: Natural killer cell (CL_0000623) in 2 different columns.
https://www.ncbi.nlm.nih.gov/pubmed/8599969
https://web.expasy.org/cellosaurus/CVCL_0466

**Comment by vtoure** [comment]
So can I summarise your comment by the following?:
It would be useful to have in causal interaction:
-  a `Cell Line` column with BRENDA terms (if Cellosaurus and BRENDA can be mapped together, it's maybe better to suggest one ontology to facilitate the later processing of causal interactions)
- a `Cell or Tissue Type` column with CL or Uberon terms

Is it possible to always depict the cell line and cell/tissue type for every single causal interactions? If not, we have to make them optional in MICAST but highly recommended to characterise whenever possible.

**Comment by ccasalsc** [comment]
Actually I wasn't familiar with Brenda, I've had a look and its ontology 
seems to me enough since we can specify between primary cells/tissues 
and tumor derived cell lines but also take the common parent if needed. 
In this case a column with BRENDA would be enough.
About the second point, usually for information coming from experimental 
data, we know the cell type. However, often we also capture information 
from author statements or coming from reviews, then we may don't know 
the cell type. So highly recommended would be the best, I guess.


-- 
Cristina Casals Casas
SIB | Swiss Institute of Bioinformatics
CMU - 1, rue Michel Servet - 1211 Geneva 4
t: +41 22 379 49 16 - f: +41 22 379 58 58
Cristina.Casals@sib.swiss - http://www.sib.swiss

**Comment by cmungall** [comment]
> a Cell Line column with BRENDA terms (if Cellosaurus and BRENDA can be mapped together, it's maybe better to suggest one ontology to facilitate the later processing of causal interactions)
> a Cell or Tissue Type column with CL or Uberon terms

This seems like a good recommendation for metazoans, with PO for plant equivalent to CL/Uberon and FAO for fungal.

(disclosure: I work on these ontologies)
